package ex1;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestCode.java
 *
 * Created on 2009. 8. 11, ?ㅼ?? 12:15:25
 */
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.LayoutManager;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pc1
 */
public class TestCode extends javax.swing.JFrame {

    private Socket sk;
    private PrintWriter pw;
    private String nickName, str, txt, ri;
    private int ptx;
    private int pty;
    private int woo = 0;
    private CardLayout card;
    private String crv;
    private Color cr;

    /**
     * Creates new form TestCode
     */
    public TestCode() {
        initComponents();

    }

    private void exe() {
        try {
            nickName = namev.getText();
            sk = new Socket("localhost", 9999); //ip랑 포트할당해서 소켓생성
            pw = new PrintWriter(sk.getOutputStream(), true); // 
        } catch (Exception ex) {
            System.out.println("연결오류");
        }
        Thread t = new Thread(new Runnable() {

            public void run() {

                BufferedReader br = null;
                try {
                    br = new BufferedReader(new InputStreamReader(sk.getInputStream()));

                    while (true) {
                        String str = br.readLine(); //읽어온다 
                        System.out.println("str :" + str);

                        StringTokenizer stn = new StringTokenizer(str, "/"); // /를 기준으로 나누는 stn생성
                        System.out.println("stn" + stn);
                        String com = stn.nextToken(); // stn를 /로 나눈 첫번째 com
                        System.out.println("com:::" + com);

                        crv = stn.nextToken(); //// stn를 /로 나눈 두번째 crv
                        System.out.println("Color" + crv);
                        ptx = Integer.parseInt(stn.nextToken()); // stn를 /로 나눈 세번째 ptx

                        if (com.equals("draw")) { // stn를 /로 나눈 첫번째 com이 draw일때 
                            pty = Integer.parseInt(stn.nextToken()); // stn를 /로 나눈 네번째 pty 
                            if (crv.equalsIgnoreCase("RED")) { //crv가 레드일때
                                cr = Color.RED; //레드
                            } else {
                                cr = Color.BLUE; //블루
                            }
                        } else if (com.equals("chat")) {// stn를 /로 나눈 첫번째 com이 draw가 아닐때
                            txt = stn.nextToken(); // stn를 /로 나눈 네번째 txt
                            txtMain.append(crv + " : " + txt + "\n"); //txtMain에 닉네임과 내용을 출력

                        } else {
                            ri = stn.nextToken();
                            clear = true;
                        }
                        can.repaint();
                    }

                } catch (IOException ex) {
                }
            }
        });
        t.start();

        can.addMouseMotionListener(new MouseMotionAdapter() {

            @Override
            public void mouseDragged(MouseEvent e) {

                int x = e.getX(); //x에 X좌표를 초기화
                int y = e.getY(); //y에 Y좌표를 초기화

                pw.println("draw" + "/" + crv + "/" + x + "/" + y);  // PCClient2에 마우스드레그일경우 이렇게 보내요
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        namev = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        can = new java.awt.Canvas(){
            @Override
            public void paint(Graphics g) {
                if ((ptx != 0) || (pty !=0)) {
                    g.setColor(cr);
                    g.fillOval(ptx, pty, 10, 10);
                }
                if(clear){

                    g.setColor(getBackground());
                    g.clearRect(0, 0, 20000, 20000);
                    clear = false;

                }
            }

            @Override
            public void update(Graphics g) {
                paint(g);
            }

        };
        userName = new javax.swing.JLabel();
        redBtn = new javax.swing.JButton();
        blueBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMain = new javax.swing.JTextArea();
        chatContent = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jScrollPane1.setViewportView(namev);

        jButton1.setText("입장");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel1.setText("우리와 종규의 채팅과 그림그리기");

        jLabel2.setText("닉네임입력");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(403, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(226, 226, 226)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, "card2");

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(757, 409));

        can.setBackground(new java.awt.Color(255, 255, 255));

        userName.setText("jLabel1");

        redBtn.setText("RED");
        redBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redBtnActionPerformed(evt);
            }
        });

        blueBtn.setText("BLUE");
        blueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueBtnActionPerformed(evt);
            }
        });

        txtMain.setColumns(20);
        txtMain.setRows(5);
        jScrollPane2.setViewportView(txtMain);

        chatContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatContentActionPerformed(evt);
            }
        });

        jButton2.setText("지우개");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(redBtn)
                        .addGap(37, 37, 37)
                        .addComponent(blueBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chatContent, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(can, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueBtn)
                    .addComponent(redBtn)
                    .addComponent(userName)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        jPanel1.add(jPanel3, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        card = (CardLayout) jPanel1.getLayout(); //카드레이아웃
        card.show(jPanel1, "card3"); //card3으로 넘어가
        userName.setText(namev.getText()); //유저네임에 저장
        exe(); //exe 실행
    }//GEN-LAST:event_jButton1ActionPerformed

    private void redBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redBtnActionPerformed
        // TODO add your handling code here:
        crv = "RED";
    }//GEN-LAST:event_redBtnActionPerformed

    private void blueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueBtnActionPerformed
        // TODO add your handling code here:
        crv = "BLUE";

    }//GEN-LAST:event_blueBtnActionPerformed

    private void chatContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatContentActionPerformed
        String str1 = chatContent.getText().trim();
        
        pw.println("chat" + "/" + namev.getText().trim() + "/" + woo + "/" + str1); // 챗팅일때 이렇게 보냄
        chatContent.setText("");
    }//GEN-LAST:event_chatContentActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //지우개 만들기
        clear = true;
        pw.println("woo/p/" + 0 + "/" + ri);
        can.repaint();


    }//GEN-LAST:event_jButton2ActionPerformed
    private boolean clear;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TestCode().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blueBtn;
    private java.awt.Canvas can;
    private javax.swing.JTextField chatContent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane namev;
    private javax.swing.JButton redBtn;
    private javax.swing.JTextArea txtMain;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
