/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2014-11-10 08:05:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/ex1_top.jsp", Long.valueOf(1415605465724L));
    _jspx_dependants.put("/ex1_bottom.jsp", Long.valueOf(1415605465720L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- 2014. 11. 3. -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"  href=\"css/style.css\" type=\"text/css\">\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<header class=\"hd\">\r\n");
      out.write("\t\t\t<h1> Include 연습 </h1>\r\n");
      out.write("\t\t\t<h2> include 지시자의 top.jsp영역\r\n");
      out.write("\t\t\t");
 if(session.getAttribute("MEMBERID")!=null) {
				String uname =(String) session.getAttribute("USERNAME");
			 
      out.write("\r\n");
      out.write("\t\t\t &nbsp;&nbsp;&nbsp;");
      out.print(uname );
      out.write("님 반갑습니다. ^^\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t </h2>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t   <ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ex1_body.jsp\">홈</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t");

					if(session.getAttribute("MEMBERID")==null){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"join.jsp\">회원가입</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"loginForm.jsp\">로그인</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t");

					}else{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage.jsp\">마이페이지</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"loginOut.jsp\">로그아웃</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"bbslist.jsp\">게시판</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"board.kosta?query=boardList&page=1\">Model2게시판</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">메뉴1</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">메뉴1</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write(" <article>\t\t \t\r\n");
      out.write(" <p>현재 IT에서 가장 각광받는 java Technology의 기초부터 고급기술까지 학습합니다\r\n");
      out.write("전자정부 프레임워크(java opensource framework)를 이용한 Enterprise Solution 설계 및 구현과 \r\n");
      out.write("안드로이드 및 하이브리드앱을 이용한 모바일 애플리케이션 구현을 학습하고 실무 프로젝트를 통해 현업에서 필요로 하는 \r\n");
      out.write("자바 엔지니어 양성을 목표로 합니다.\t\r\n");
      out.write("\t\t \t</p>\r\n");
      out.write("\t\t \t<section>\r\n");
      out.write("\t\t \t<header style=\"margin: auto; width: 100%;\"><h2>BoardForm Page</h2></header>\r\n");
      out.write("\t\t \t<p >\r\n");
      out.write("\t\t \t\t<form method=\"post\" action=\"board.kosta\">\r\n");
      out.write("\t\t \t\t<input type=\"hidden\" name=\"query\" value=\"boardAdd\">\r\n");
      out.write("\t\t \t\t<table style=\"margin: auto; width: 400px;border:1px solid black;border-collapse: collapse;\">\r\n");
      out.write("\t\t \t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t<td>제목</td>\r\n");
      out.write("\t\t \t\t\t\t<td><input type=\"text\" name=\"title\">\r\n");
      out.write("\t\t \t\t\t\t</td>\r\n");
      out.write("\t\t \t\t\t</tr>\r\n");
      out.write("\t\t \t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t<td>작성자</td>\r\n");
      out.write("\t\t \t\t\t\t<td><input type=\"text\" name=\"writer\" id=\"writer\"></td>\r\n");
      out.write("\t\t \t\t\t</tr>\r\n");
      out.write("\t\t \t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t<td>groupno</td>\r\n");
      out.write("\t\t \t\t\t\t<td><input type=\"number\" name=\"groupno\"></td>\r\n");
      out.write("\t\t \t\t\t</tr>\r\n");
      out.write("\t\t \t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t<td>내용</td>\r\n");
      out.write("\t\t \t\t\t\t<td>\r\n");
      out.write("\t\t \t\t\t\t<textarea rows=\"10\" cols=\"52\" name=\"content\"></textarea>\r\n");
      out.write("\t\t \t\t\t\t</td>\r\n");
      out.write("\t\t \t\t\t</tr>\r\n");
      out.write("\t\t \t\t\t<tr><td colspan=\"2\" style=\"text-align: right;\">\r\n");
      out.write("\t\t \t\t\t\t<input type=\"submit\" value=\"글작성\"\r\n");
      out.write("\t\t \t\t\t\t\tstyle=\"width: 100px; height: 30px;\"\r\n");
      out.write("\t\t \t\t\t\t\t\r\n");
      out.write("\t\t \t\t\t\t>&nbsp;\r\n");
      out.write("\t\t \t\t\t\t<input type=\"button\" value=\"리스트\"\r\n");
      out.write("\t\t \t\t\t\t\tstyle=\"width: 100px; height: 30px;\"\r\n");
      out.write("\t\t \t\t\t\t\tonclick=\"location='board.kosta?query=boardList&page=1'\"\r\n");
      out.write("\t\t \t\t\t\t>\r\n");
      out.write("\t\t \t\t\t</td></tr>\r\n");
      out.write("\t\t \t\t</table>\r\n");
      out.write("\t\t \t\t</form>\r\n");
      out.write("\t\t \t</p>\r\n");
      out.write("\t\t \t</section>\r\n");
      out.write("\t\t </article>\t\r\n");
      out.write("\t\t  <aside>\r\n");
      out.write("        <header>\r\n");
      out.write("            <h1>Siderbar Heading</h1>\r\n");
      out.write("        </header>\r\n");
      out.write("        <p>문서의 주 내용이 아닌 관련성이 낮은 내용들은 aside로 표시할 수 있다.\r\n");
      out.write("\t\t본문과 직접적으로 상관이 없는 관련 사이트 링크나 안내글, nav 요소의 그룹 등이 aside 요소로 기술 될 수 있다.\r\n");
      out.write("\t\t보통 블로그에서 좌우측 사이드바를 의미하는 것으로서 사이드바의 특성으로 볼때 필수적이지 않아서 표시를 해도 되고 안 해도 되는 내용들 또는 광고물같은 내용들이 자리할 수 있다.</p>\r\n");
      out.write("\r\n");
      out.write("    </aside>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write(" <footer>\r\n");
      out.write("\t\t \t<nav>\r\n");
      out.write("\t\t\t   <ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">회사주소</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">이용약관</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">회사약도</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">연혁</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">개인정보정책</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">제휴회사</a>&nbsp; |</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">Sitemap</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t </footer>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
